openapi: 3.1.1
info:
  title: Retail — Food and Beverage Item Attributes (v1)
  version: 1.0.0
  x-profile-id: profiles/retail/food-and-beverage/v1/food-and-beverage-item
  description: >
    Food and Beverage-specific item attributes intended to be attached to
    Item.attributes (beckn:itemAttributes) for F&B food and beverage catalogs on Beckn/ONDC.

    This pack only models attributes that are **not** already covered by the
    core Beckn Item schema. It focuses on dietary classification and
    configuration hooks observed in ONDC F&B examples.

components:
  schemas:
    ########################################################################
    # ITEM.ATTRIBUTES — FoodAndBeverageItem
    ########################################################################
    FoodAndBeverageItem:
      type: object
      additionalProperties: false
      description: >
        Food and Beverage-specific item attributes (dietary flags, configuration hooks,
        and domain category) to be composed with the core Beckn Item via
        beckn:itemAttributes.
      properties:

        ######################################################################
        # Domain category (to be linked to core CategoryCode via JSON-LD)
        ######################################################################
        category:
          type: string
          enum: ["PIZZA"]
          description: >
            Domain category for this item within the F&B profile. This can be
            linked to the core beckn:CategoryCode (e.g., "Food and Beverage") via JSON-LD
            equivalence in the context.

        ######################################################################
        # Dietary classification
        ######################################################################
        dietaryClassification:
          type: string
          enum: [veg, "non-veg"]
          description: >
            Dietary classification for the item (veg or non-veg), as
            represented via ONDC F&B `veg_nonveg` tags.
          example: "veg"

        ######################################################################
        # Customization options (for pizza)
        ######################################################################
        crust:
          type: string
          enum: ["New Hand Tossed", "Thin Crust", "Thick Crust", "Cheese Burst", "Wheat Thin Crust"]
          description: >
            Crust type selection for the pizza (any 1 option required).
            Derived from ONDC F&B customization group CG1.
          example: "New Hand Tossed"

        size:
          type: string
          enum: ["Regular", "Medium", "Large", "Personal", "Family"]
          description: >
            Size selection for the pizza (any 1 option required).
            Derived from ONDC F&B customization group CG2.
          example: "Regular"

        toppings:
          type: array
          maxItems: 2
          description: >
            Toppings selection for the pizza (up to 2 options allowed).
            Derived from ONDC F&B customization group CG3.
          items:
            type: string
            enum: ["Grilled Mushrooms", "Pepperoni", "Olives", "Onions", "Capsicum", "Jalapenos", "Paneer", "Corn", "Tomatoes"]
          example: ["Grilled Mushrooms"]



