@startuml
hide empty members
set namespaceSeparator none


class EnergyTradeOffer {
    {field} string <b>pricingModel</b> {"PER_KWH", "TIME_OF_DAY", "SUBSCRIPTION", "FIXED"}
    {field} string settlementType {"REAL_TIME", "HOURLY", "DAILY", "WEEKLY", "MONTHLY"}
    {field} string sourceMeterId
    {field} object wheelingCharges
    {field} number minimumQuantity
    {field} number maximumQuantity
    {field} TimePeriod validityWindow
    {field} object[] timeOfDayRates
    {field} PriceSpecification beckn:price
    {field} Quantity beckn:maxQuantity
    {field} TimePeriod beckn:timeWindow
}

EnergyTradeOffer ..> PriceSpecification
EnergyTradeOffer ..> Quantity
EnergyTradeOffer ..> TimePeriod

@enduml
