openapi: 3.1.1
info:
  title: Energy Trade — Customer Attributes (v0.1)
  version: 0.1.0
  x-profile-id: profiles/energy-trade/energy_trade/v0.1/customer
  description: >
    Attribute schemas for energy customers (Buyer.buyerAttributes and Provider.providerAttributes).
    These attributes are attached to Buyer.buyerAttributes or Provider.providerAttributes to provide energy-specific
    customer information including meter identification and sanctioned load for consumers, producers, or prosumers
    in P2P energy trading and program enrollment flows.

components:
  schemas:
    ########################################################################
    # CUSTOMER.ATTRIBUTES — EnergyCustomer (P2P Energy Trading & Enrollment)
    ########################################################################
    EnergyCustomer:
      type: object
      additionalProperties: false
      required: ["meterId"]
      x-jsonld:
        "@context": ./context.jsonld
        "@type": EnergyCustomer
      description: >
        Customer attributes for energy flows. Used for consumers, producers, or prosumers in:
        - orderItemAttributes (init request): Contains meterId for delivery destination
        - orderItemAttributes (responses): Contains meterId for delivery destination
        - buyerAttributes (enrollment): Contains meterId and sanctionedLoad for customer identification
      properties:

        meterId:
          type: string
          description: >
            Meter identifier in DER address format (der://meter/{id}). Used for customer identification
            and energy delivery tracking in P2P trading flows.
          example: "der://meter/98765456"
          x-jsonld: { "@id": meterId }

        sanctionedLoad:
          type: number
          minimum: 0
          description: >
            Sanctioned load capacity in kilowatts (kW). Optional field representing the approved
            electrical load capacity for the customer's connection. Used for load management and
            regulatory compliance.
          example: 15.0
          x-jsonld: { "@id": sanctionedLoad }

        utilityCustomerId:
          type: string
          description: >
            Customer's account identifier with the utility company (e.g., PG&E customer number).
            Used for billing, service identification, and utility system integration.
          example: "UTIL-CUST-123456"
          x-jsonld: { "@id": utilityCustomerId }
