openapi: 3.1.1
info:
  title: Energy Trade — Energy Resource Attributes (v0.2)
  version: 0.2.0
  x-profile-id: profiles/energy-trade/energy_trade/v0.2/energy-resource
  description: >
    Attribute schemas for energy resources (Item.attributes).
    These attributes are attached to Item.itemAttributes to provide energy-specific 
    characteristics including source type, delivery mode, certification status, 
    meter identifiers, and availability details for P2P energy trading.

components:
  schemas:
    ########################################################################
    # ITEM.ATTRIBUTES — EnergyResource (P2P Energy Trading)
    ########################################################################
    EnergyResource:
      type: object
      additionalProperties: false
      x-jsonld:
        "@context": ./context.jsonld
        "@type": EnergyResource
      properties:

        sourceType:
          type: string
          enum: [SOLAR, BATTERY, GRID, HYBRID, RENEWABLE]
          description: Type of energy source. Source verification occurs at onboarding but can change post-onboarding (e.g., switching from solar to diesel). Source type influences price but not workflow.
          example: "SOLAR"
          x-jsonld: { "@id": sourceType }

        deliveryMode:
          type: string
          enum: [EV_CHARGING, BATTERY_SWAP, V2G, GRID_INJECTION]
          description: Mode of energy delivery. Used as discovery filter to match consumer requirements.
          example: "GRID_INJECTION"
          x-jsonld: { "@id": deliveryMode }

        certificationStatus:
          type: string
          description: Carbon offset or green energy certification status (e.g., "Carbon Offset Certified", "Green Energy Certified").
          example: "Carbon Offset Certified"
          x-jsonld: { "@id": certificationStatus }

        meterId:
          type: string
          description: Source meter identifier in DER address format (der://meter/{id}). Used for discovery and fulfillment tracking.
          example: "der://meter/100200300"
          x-jsonld: { "@id": meterId }

        inverterId:
          type: string
          description: Inverter identifier serving as consistent interface between source and grid. Remains constant even if source changes.
          example: "inv-12345"
          x-jsonld: { "@id": inverterId }

        availableQuantity:
          type: number
          minimum: 0
          description: Available energy quantity in kilowatt-hours (kWh).
          example: 30.5
          x-jsonld: { "@id": availableQuantity }

        productionWindow:
          type: object
          description: Time window when energy is produced or available for trading.
          x-jsonld: { "@id": productionWindow }
          additionalProperties: false
          properties:
            start:
              type: string
              format: date-time
              description: Start time of production/availability window (ISO 8601).
              example: "2024-10-04T10:00:00Z"
              x-jsonld: { "@id": "schema:startTime" }
            end:
              type: string
              format: date-time
              description: End time of production/availability window (ISO 8601).
              example: "2024-10-04T18:00:00Z"
              x-jsonld: { "@id": "schema:endTime" }

        sourceVerification:
          type: object
          description: Source verification details including certificates and verification status.
          x-jsonld: { "@id": sourceVerification }
          additionalProperties: false
          properties:
            verified:
              type: boolean
              description: Whether the source has been verified.
              example: true
              x-jsonld: { "@id": verified }
            verificationDate:
              type: string
              format: date-time
              description: Date when source was last verified.
              example: "2024-09-01T00:00:00Z"
              x-jsonld: { "@id": verificationDate }
            certificates:
              type: array
              description: Array of certificate references (URLs or identifiers).
              items:
                type: string
                format: uri
              example: ["https://example.com/certs/solar-panel-cert.pdf"]
              x-jsonld: { "@id": certificates }

        productionAsynchronous:
          type: boolean
          description: Whether production and trade may be asynchronous (before, during, or after the transaction).
          example: true
          default: false
          x-jsonld: { "@id": productionAsynchronous }

