@startuml
hide empty members
set namespaceSeparator none


class EnergyResource {
    {field} string sourceType {"SOLAR", "BATTERY", "GRID", "HYBRID", "RENEWABLE"}
    {field} string deliveryMode {"EV_CHARGING", "BATTERY_SWAP", "V2G", "GRID_INJECTION"}
    {field} string certificationStatus
    {field} string meterId
    {field} number availableQuantity
    {field} TimePeriod[] productionWindow
    {field} object sourceVerification
    {field} boolean productionAsynchronous = false
}

EnergyResource ..> TimePeriod

@enduml
