@startuml
hide empty members
set namespaceSeparator none


class ChargingPointOperator {
    {field} string operatorName
    {field} string operatorCode
    {field} string identifier
    {field} string (uri) sameAs
    {field} string (email) supportEmail
    {field} string supportPhone
    {field} string gstNumber
    {field} string cin
    {field} string msme
    {field} object operatorContact
}


@enduml
