required key "type" not found in dictionary {"description": "User authentication request - sent by BAP to BPP in init/confirm requests. Supports OTP-based or OAuth2/OIDC token-based authentication.\n", "oneOf": [{"$ref": "#/components/schemas/OtpAuthRequest"}, {"$ref": "#/components/schemas/OAuth2AuthRequest"}], "discriminator": {"propertyName": "authMethod", "mapping": {"OTP": "#/components/schemas/OtpAuthRequest", "OAUTH2": "#/components/schemas/OAuth2AuthRequest", "OIDC": "#/components/schemas/OAuth2AuthRequest"}}}
Traceback (most recent call last):
  File "/Users/ameetdeshpande/.pyenv/versions/3.14.0b3/bin/swagger_to_uml", line 385, in <module>
    sw = Swagger.from_file(input_file_name)
  File "/Users/ameetdeshpande/.pyenv/versions/3.14.0b3/bin/swagger_to_uml", line 372, in from_file
    return Swagger.from_dict(loader(fd))
           ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
  File "/Users/ameetdeshpande/.pyenv/versions/3.14.0b3/bin/swagger_to_uml", line 360, in from_dict
    definitions.extend([Definition.from_dict(name, definition) for name, definition in d['components']['schemas'].items()])
                        ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "/Users/ameetdeshpande/.pyenv/versions/3.14.0b3/bin/swagger_to_uml", line 203, in from_dict
    type=d['type'],
         ~^^^^^^^^
KeyError: 'type'
