openapi: 3.1.1
info:
  title: Energy Trade — Order Item Attributes (v0.1)
  version: 0.1.0
  x-profile-id: profiles/energy-trade/energy_order_item/v0.1/order-item
  description: >
    Attribute schemas for energy trade order items (orderItemAttributes).
    This schema wraps customer information and optional fulfillment tracking data.
    Use this schema for beckn:orderItemAttributes in P2P energy trading flows.

components:
  schemas:
    ########################################################################
    # ORDERITEM.ATTRIBUTES — EnergyOrderItem (P2P Energy Trading)
    ########################################################################
    EnergyOrderItem:
      type: object
      additionalProperties: false
      x-jsonld:
        "@context": ./context.jsonld
        "@type": EnergyOrderItem
      properties:

        providerAttributes:
          type: object
          description: >
            Provider/customer information for this order item, including meter ID and utility account.
          additionalProperties: true
          properties:
            "@context":
              type: string
              format: uri
              description: URI to the EnergyCustomer context.jsonld
            "@type":
              type: string
              enum: ["EnergyCustomer"]
              description: Type identifier for provider attributes
          x-jsonld: { "@id": providerAttributes }

        fulfillmentAttributes:
          type: object
          description: >
            Optional fulfillment tracking for this order item.
            Only populated in on_status and on_update responses (not in init/confirm flows).
            Contains delivery status, meter readings, and energy allocation data.
          additionalProperties: true
          properties:
            "@context":
              type: string
              format: uri
              description: URI to the EnergyTradeDelivery context.jsonld
            "@type":
              type: string
              enum: ["EnergyTradeDelivery"]
              description: Type identifier for fulfillment attributes
          x-jsonld: { "@id": fulfillmentAttributes }

      required:
        - providerAttributes
