@startuml
hide empty members
set namespaceSeparator none


class ChargingOffer {
    {field} string tariffModel {"PER_KWH", "PER_MINUTE", "SUBSCRIPTION", "TIME_OF_DAY"}
    {field} PriceSpecification idleFeePolicy
}

ChargingOffer ..> PriceSpecification

@enduml
