openapi: 3.1.1
info:
  title: Energy Trade — Provider Attributes (v0.2)
  version: 0.2.0
  x-profile-id: profiles/energy-trade/energy_trade/v0.2/provider
  description: >
    Attribute schemas for energy providers (Provider.providerAttributes).
    These attributes are attached to Provider.providerAttributes to provide energy-specific
    provider information including source meter identification for P2P energy trading.
    Utility BPP validates source meter ID during offer processing.

components:
  schemas:
    ########################################################################
    # PROVIDER.ATTRIBUTES — EnergyProvider (P2P Energy Trading)
    ########################################################################
    EnergyProvider:
      type: object
      additionalProperties: false
      x-jsonld:
        "@context": ./context.jsonld
        "@type": EnergyProvider
      properties:

        sourceMeterId:
          type: string
          description: Source meter identifier in DER address format (der://meter/{id}) where energy originates. Validated by utility BPP against grid registry during offer discovery and order processing.
          example: "der://meter/100200300"
          x-jsonld: { "@id": sourceMeterId }

        sourceType:
          type: string
          enum: [SOLAR, BATTERY, GRID, HYBRID, RENEWABLE]
          description: Type of energy source. Source verification occurs at onboarding but can change post-onboarding (e.g., switching from solar to diesel). Source type influences price but not workflow.
          example: "SOLAR"
          x-jsonld: { "@id": sourceType }

        certification:
          type: object
          description: Energy certification details including status and certificates.
          x-jsonld: { "@id": certification }
          additionalProperties: false
          properties:
            status:
              type: string
              description: Certification status (e.g., "Carbon Offset Certified", "Green Energy Certified").
              example: "Carbon Offset Certified"
              x-jsonld: { "@id": "schema:name" }
            certificates:
              type: array
              description: Array of certificate references (URLs or identifiers).
              items:
                type: string
                format: uri
              example: ["https://example.com/certs/solar-panel-cert.pdf"]
              x-jsonld: { "@id": certificates }

