openapi: 3.1.1
info:
  title: Energy Trade — Trade Delivery Attributes (v0.2)
  version: 0.2.0
  x-profile-id: profiles/energy-trade/energy_trade/v0.2/trade-delivery
  description: >
    Attribute schemas for energy trade deliveries (orderItemAttributes.fulfillmentAttributes).
    These attributes track physical transfer of energy between source and target, including
    delivery status, meter readings with time windows, and energy allocation data.
    Per IEC 61968/NAESB ESPI standards: deliveredEnergy = energy TO customer (imported),
    receivedEnergy = energy FROM customer (exported to grid).

components:
  schemas:
    ########################################################################
    # FULFILLMENT.ATTRIBUTES — EnergyTradeDelivery (P2P Energy Trading)
    ########################################################################
    EnergyTradeDelivery:
      type: object
      additionalProperties: false
      x-jsonld:
        "@context": ./context.jsonld
        "@type": EnergyTradeDelivery
      properties:

        deliveryStatus:
          type: string
          enum: [PENDING, IN_PROGRESS, COMPLETED, FAILED]
          description: Delivery status for the energy transfer.
          example: "IN_PROGRESS"
          x-jsonld: { "@id": deliveryStatus }

        deliveryMode:
          type: string
          enum: [EV_CHARGING, BATTERY_SWAP, V2G, GRID_INJECTION]
          description: Mode of energy delivery for this fulfillment.
          example: "GRID_INJECTION"
          x-jsonld: { "@id": deliveryMode }

        deliveredQuantity:
          type: number
          minimum: 0
          description: Total quantity delivered so far in kilowatt-hours (kWh).
          example: 15.0
          x-jsonld: { "@id": deliveredQuantity }

        meterReadings:
          type: array
          description: >
            Array of meter readings for this orderItem. Each reading covers a time window
            and reports energy delivered/received during that period. Times are in UTC (ISO 8601 with Z suffix).
          items:
            type: object
            additionalProperties: false
            properties:
              beckn:timeWindow:
                type: object
                description: Time period for this meter reading (UTC).
                additionalProperties: false
                properties:
                  "@type":
                    type: string
                    enum: ["beckn:TimePeriod"]
                  schema:startTime:
                    type: string
                    format: date-time
                    pattern: '^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}(\.\d+)?Z$'
                    description: Start time in UTC (ISO 8601 with Z suffix).
                  schema:endTime:
                    type: string
                    format: date-time
                    pattern: '^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}(\.\d+)?Z$'
                    description: End time in UTC (ISO 8601 with Z suffix).
                required: ["schema:startTime", "schema:endTime"]
              deliveredEnergy:
                type: number
                minimum: 0
                description: >
                  Energy delivered TO the customer (imported from grid) in this time window (kWh).
                  Per IEC 61968/ESPI flowDirection=1.
                x-jsonld: { "@id": deliveredEnergy }
              receivedEnergy:
                type: number
                minimum: 0
                description: >
                  Energy received FROM the customer (exported to grid) in this time window (kWh).
                  Per IEC 61968/ESPI flowDirection=19.
                x-jsonld: { "@id": receivedEnergy }
              allocatedEnergy:
                type: number
                minimum: 0
                description: Net energy allocated for this trade in this time window (kWh).
                x-jsonld: { "@id": allocatedEnergy }
              unit:
                type: string
                enum: ["kWh", "MWh", "Wh"]
                default: "kWh"
                description: Unit of measurement for energy values.
                x-jsonld: { "@id": "schema:unitText" }
            required: ["beckn:timeWindow", "allocatedEnergy", "unit"]
          x-jsonld: { "@id": meterReadings }

        curtailedQuantity:
          type: number
          minimum: 0
          description: >
            Quantity curtailed from original contracted amount (kWh).
            Used by BAP/BPP to reconcile payment vs. original contracted quantity.
          example: 5.0
          x-jsonld: { "@id": curtailedQuantity }

        curtailmentReason:
          type: string
          enum: [GRID_OUTAGE, EMERGENCY, CONGESTION, MAINTENANCE, OTHER]
          description: Reason for curtailment. Useful for audit trail and dispute resolution.
          example: "GRID_OUTAGE"
          x-jsonld: { "@id": curtailmentReason }

        lastUpdated:
          type: string
          format: date-time
          description: Last delivery update timestamp in UTC (ISO 8601 with Z suffix).
          example: "2024-10-04T15:30:00Z"
          x-jsonld: { "@id": "schema:dateModified" }
