openapi: 3.1.1
info:
  title: Retail — Food and Beverage Fulfillment Attributes (v1)
  version: 1.0.0
  x-profile-id: profiles/retail/food-and-beverage/v1/food-and-beverage-fulfillment
  description: >
    Food and Beverage fulfillment attributes intended to be attached to Order.fulfillments[].attributes
    or Provider-level fulfillment attributes for food and beverage/F&B catalogs on Beckn/ONDC.

    This pack models fulfillment capabilities, contact information, timing policies,
    closure windows, and serviceability rules specific to food and beverage/F&B retail, derived
    from ONDC F&B examples.

components:
  schemas:
    ########################################################################
    # FULFILLMENT.ATTRIBUTES — FoodAndBeverageFulfillment
    ########################################################################
    FoodAndBeverageFulfillment:
      type: object
      additionalProperties: false
      description: >
        Food and Beverage fulfillment attributes (supported types, contact info, timing policies,
        closure windows, and serviceability) to be attached to fulfillment objects.
      properties:

        ######################################################################
        # Supported fulfillment types
        ######################################################################
        supportedFulfillmentTypes:
          type: array
          description: >
            Array of fulfillment types supported by this provider/channel
            (e.g., Delivery, Self-Pickup, Delivery and Self-Pickup).
          items:
            type: string
            enum: [Delivery, Self-Pickup, "Delivery and Self-Pickup"]
          example: ["Delivery", "Self-Pickup"]

        ######################################################################
        # Contact information
        ######################################################################
        contactPhone:
          type: string
          description: >
            Contact phone number for fulfillment-related inquiries.
          example: "9886098860"

        contactEmail:
          type: string
          format: email
          description: >
            Contact email address for fulfillment-related inquiries.
          example: "abc@xyz.com"

        ######################################################################
        # Timing policies (operating hours per fulfillment type and location)
        ######################################################################
        timingPolicies:
          type: array
          description: >
            Timing policies defining operating hours for different fulfillment types
            (Order, Delivery, Self-Pickup) per location. Transformed from ONDC
            timing tags.
          items:
            type: object
            additionalProperties: false
            required: [fulfillmentType, locationId]
            properties:
              fulfillmentType:
                type: string
                enum: [Order, Delivery, Self-Pickup]
                description: >
                  Type of fulfillment operation this timing policy applies to.
                example: "Order"
              locationId:
                type: string
                description: >
                  Location identifier where this timing policy applies.
                example: "L1"
              dayFrom:
                type: integer
                minimum: 1
                maximum: 7
                description: >
                  Starting day of week (1=Monday, 7=Sunday) for this timing window.
                example: 1
              dayTo:
                type: integer
                minimum: 1
                maximum: 7
                description: >
                  Ending day of week (1=Monday, 7=Sunday) for this timing window.
                example: 5
              timeFrom:
                type: string
                pattern: '^[0-9]{4}$'
                description: >
                  Starting time in HHMM format (24-hour, e.g., "0900" for 9:00 AM).
                example: "0900"
              timeTo:
                type: string
                pattern: '^[0-9]{4}$'
                description: >
                  Ending time in HHMM format (24-hour, e.g., "2200" for 10:00 PM).
                example: "2200"
          example:
            - fulfillmentType: "Order"
              locationId: "L1"
              dayFrom: 1
              dayTo: 5
              timeFrom: "0900"
              timeTo: "1100"
            - fulfillmentType: "Delivery"
              locationId: "L1"
              dayFrom: 1
              dayTo: 7
              timeFrom: "1100"
              timeTo: "2200"

        ######################################################################
        # Closure / downtime windows
        ######################################################################
        closeTiming:
          type: array
          description: >
            Closure or downtime windows when fulfillment operations are temporarily
            unavailable at specific locations. Transformed from ONDC close_timing tags.
          items:
            type: object
            additionalProperties: false
            required: [locationId, start, end]
            properties:
              locationId:
                type: string
                description: >
                  Location identifier where this closure applies.
                example: "L1"
              start:
                type: string
                format: date-time
                description: >
                  Start timestamp of the closure window (ISO 8601 UTC).
                example: "2025-01-08T16:00:00.000Z"
              end:
                type: string
                format: date-time
                description: >
                  End timestamp of the closure window (ISO 8601 UTC).
                example: "2025-01-08T23:59:00.000Z"
          example:
            - locationId: "L1"
              start: "2025-01-08T16:00:00.000Z"
              end: "2025-01-08T23:59:00.000Z"

        ######################################################################
        # Serviceability (where & for which categories fulfillment is available)
        ######################################################################
        serviceability:
          type: array
          description: >
            Serviceability rules defining where and for which categories the
            provider can fulfill orders. Transformed from ONDC serviceability tags.
          items:
            type: object
            additionalProperties: false
            required: [locationId, category]
            properties:
              locationId:
                type: string
                description: >
                  Location identifier where this serviceability rule applies.
                example: "L1"
              category:
                type: string
                description: >
                  Category name or code for which this serviceability applies
                  (e.g., "F&B").
                example: "F&B"
              serviceabilityCode:
                type: string
                enum: ["10", "12"]
                description: >
                  Serviceability code indicating the type of constraint
                  ("10" for distance-based, "12" for country-wide).
                example: "10"
              serviceabilityType:
                type: string
                enum: [distance-based, country-wide]
                description: >
                  Type of serviceability constraint (distance-based or country-wide).
                example: "distance-based"
              value:
                type: string
                description: >
                  Value of the serviceability constraint (e.g., numeric radius).
                example: "3"
              unit:
                type: string
                enum: [km]
                description: >
                  Unit of the serviceability value (e.g., "km" for distance).
                example: "km"
          example:
            - locationId: "L1"
              category: "F&B"
              serviceabilityCode: "10"
              serviceabilityType: "distance-based"
              value: "3"
              unit: "km"

