openapi: 3.1.1
info:
  title: Energy Trade — Trade Contract Attributes (v0.2)
  version: 0.2.0
  x-profile-id: profiles/energy-trade/energy_trade/v0.2/trade-contract
  description: >
    Attribute schemas for energy trade contracts (Order.attributes).
    These attributes are attached to Order.orderAttributes to track commercial agreements
    for energy transactions, including contract status, meter identifiers, settlement cycles,
    billing cycles, and energy delivery details.

components:
  schemas:
    ########################################################################
    # ORDER.ATTRIBUTES — EnergyTradeContract (P2P Energy Trading)
    ########################################################################
    EnergyTradeContract:
      type: object
      additionalProperties: false
      x-jsonld:
        "@context": ./context.jsonld
        "@type": EnergyTradeContract
      properties:

        contractStatus:
          type: string
          enum: [PENDING, ACTIVE, COMPLETED, TERMINATED]
          description: Contract lifecycle status. Decouples trade from fulfillment - generator, transmitter, and consumer operate independently.
          example: "ACTIVE"
          x-jsonld: { "@id": contractStatus }

        sourceMeterId:
          type: string
          description: Source meter identifier in DER address format (der://meter/{id}). Identifies the energy generator.
          example: "der://meter/100200300"
          x-jsonld: { "@id": sourceMeterId }

        targetMeterId:
          type: string
          description: Target/consumer meter identifier in DER address format (der://meter/{id}). Identifies the energy consumer.
          example: "der://meter/98765456"
          x-jsonld: { "@id": targetMeterId }

        inverterId:
          type: string
          description: Inverter identifier serving as consistent interface between source and grid. Remains constant even if source changes.
          example: "inv-12345"
          x-jsonld: { "@id": inverterId }

        contractedQuantity:
          type: number
          minimum: 0
          description: Contracted energy quantity in kilowatt-hours (kWh).
          example: 10.0
          x-jsonld: { "@id": contractedQuantity }

        tradeStartTime:
          type: string
          format: date-time
          description: Contract start time (ISO 8601).
          example: "2024-10-04T10:00:00Z"
          x-jsonld: { "@id": "schema:startTime" }

        tradeEndTime:
          type: string
          format: date-time
          description: Contract end time (ISO 8601). Null for ongoing contracts.
          example: "2024-10-04T18:00:00Z"
          x-jsonld: { "@id": "schema:endTime" }

        sourceType:
          type: string
          enum: [SOLAR, BATTERY, GRID, HYBRID, RENEWABLE]
          description: Energy source type at contract time. May differ from current source type.
          example: "SOLAR"
          x-jsonld: { "@id": sourceType }

        certification:
          type: object
          description: Energy certification details at contract time.
          x-jsonld: { "@id": certification }
          additionalProperties: false
          properties:
            status:
              type: string
              description: Certification status (e.g., "Carbon Offset Certified", "Green Energy Certified").
              example: "Carbon Offset Certified"
              x-jsonld: { "@id": "schema:name" }
            certificates:
              type: array
              description: Array of certificate references (URLs or identifiers).
              items:
                type: string
                format: uri
              example: ["https://example.com/certs/solar-panel-cert.pdf"]
              x-jsonld: { "@id": certificates }

        settlementCycles:
          type: array
          description: Array of settlement cycles for recurring contracts. Supports single order with multiple billing or fulfillment cycles.
          items:
            type: object
            additionalProperties: false
            properties:
              cycleId:
                type: string
                description: Unique settlement cycle identifier.
                example: "settle-2024-10-04-001"
                x-jsonld: { "@id": cycleId }
              startTime:
                type: string
                format: date-time
                description: Settlement cycle start time (ISO 8601).
                example: "2024-10-04T00:00:00Z"
                x-jsonld: { "@id": "schema:startTime" }
              endTime:
                type: string
                format: date-time
                description: Settlement cycle end time (ISO 8601).
                example: "2024-10-04T23:59:59Z"
                x-jsonld: { "@id": "schema:endTime" }
              status:
                type: string
                enum: [PENDING, SETTLED, FAILED]
                description: Settlement cycle status.
                example: "SETTLED"
                x-jsonld: { "@id": status }
              amount:
                type: number
                minimum: 0
                description: Settlement amount for this cycle.
                example: 50.0
                x-jsonld: { "@id": "schema:amount" }
              currency:
                type: string
                description: Currency code (ISO 4217).
                example: "USD"
                x-jsonld: { "@id": "schema:currency" }
          x-jsonld: { "@id": settlementCycles }

        billingCycles:
          type: array
          description: Array of billing periods for the contract. Supports ongoing connections billed periodically.
          items:
            type: object
            additionalProperties: false
            properties:
              cycleId:
                type: string
                description: Unique billing cycle identifier.
                example: "bill-2024-10-001"
                x-jsonld: { "@id": cycleId }
              startTime:
                type: string
                format: date-time
                description: Billing cycle start time (ISO 8601).
                example: "2024-10-01T00:00:00Z"
                x-jsonld: { "@id": "schema:startTime" }
              endTime:
                type: string
                format: date-time
                description: Billing cycle end time (ISO 8601).
                example: "2024-10-31T23:59:59Z"
                x-jsonld: { "@id": "schema:endTime" }
              status:
                type: string
                enum: [PENDING, PAID, OVERDUE]
                description: Billing cycle payment status.
                example: "PAID"
                x-jsonld: { "@id": status }
              totalAmount:
                type: number
                minimum: 0
                description: Total billing amount for this cycle.
                example: 150.0
                x-jsonld: { "@id": "schema:amount" }
              currency:
                type: string
                description: Currency code (ISO 4217).
                example: "USD"
                x-jsonld: { "@id": "schema:currency" }
              lineItems:
                type: array
                description: Billing line items including energy cost and wheeling charges.
                items:
                  type: object
                  additionalProperties: false
                  properties:
                    title:
                      type: string
                      description: Line item title.
                      example: "Energy Cost"
                      x-jsonld: { "@id": "schema:name" }
                    amount:
                      type: number
                      minimum: 0
                      description: Line item amount.
                      example: 100.0
                      x-jsonld: { "@id": "schema:amount" }
                    currency:
                      type: string
                      description: Currency code (ISO 4217).
                      example: "USD"
                      x-jsonld: { "@id": "schema:currency" }
                x-jsonld: { "@id": lineItems }
          x-jsonld: { "@id": billingCycles }

        wheelingCharges:
          type: object
          description: Utility wheeling charges breakdown (e.g., PG&E fixed charges).
          x-jsonld: { "@id": wheelingCharges }
          additionalProperties: false
          properties:
            utilityName:
              type: string
              description: Name of the utility providing wheeling services.
              example: "PG&E Grid Services"
              x-jsonld: { "@id": "schema:name" }
            amount:
              type: number
              minimum: 0
              description: Total wheeling charge amount.
              example: 2.5
              x-jsonld: { "@id": "schema:amount" }
            currency:
              type: string
              description: Currency code (ISO 4217).
              example: "USD"
              x-jsonld: { "@id": "schema:currency" }
            description:
              type: string
              description: Description of wheeling charges.
              example: "Fixed wheeling charges for grid transmission"
              x-jsonld: { "@id": "schema:description" }

        lastUpdated:
          type: string
          format: date-time
          description: Last contract update timestamp (UTC).
          example: "2024-10-04T15:30:00Z"
          x-jsonld: { "@id": "schema:dateModified" }

