openapi: 3.1.1
info:
  title: Energy Trade — Trade Order Attributes (v0.2)
  version: 0.2.0
  x-profile-id: profiles/energy-trade/energy_trade/v0.2/trade-order
  description: >
    Attribute schemas for energy trade orders (Order.attributes).
    These attributes are attached to Order.orderAttributes to identify the
    BAP and BPP participants involved in a P2P energy trade, along with order quantity details.

components:
  schemas:
    ########################################################################
    # ORDER.ATTRIBUTES — EnergyTradeOrder (P2P Energy Trading)
    ########################################################################
    EnergyTradeOrder:
      type: object
      # Note: additionalProperties not set to false to allow allOf composition
      # with EnergyTradeOrderInterUtility and future extensions
      required: [bap_id, bpp_id]
      x-jsonld:
        "@context": ./context.jsonld
        "@type": EnergyTradeOrder
      properties:

        bap_id:
          type: string
          description: Beckn Application Platform (BAP) identifier. The subscriber ID of the buyer/consumer platform initiating the trade order.
          example: "bap.energymarket.io"
          x-jsonld: { "@id": bap_id }

        bpp_id:
          type: string
          description: Beckn Provider Platform (BPP) identifier. The subscriber ID of the seller/provider platform fulfilling the trade order.
          example: "bpp.solarprovider.io"
          x-jsonld: { "@id": bpp_id }

        total_quantity:
          type: number
          minimum: 0
          description: Total quantity of energy in kilowatt-hours (kWh) for this trade order.
          example: 50.0
          x-jsonld: { "@id": total_quantity }

    ########################################################################
    # ORDER.ATTRIBUTES — EnergyTradeOrderInterUtility (Inter-Discom P2P Trading)
    ########################################################################
    EnergyTradeOrderInterUtility:
      description: >
        Extended energy trade order attributes for inter-utility (inter-discom) P2P trading.
        Inherits all properties from EnergyTradeOrder and adds utility/discom identifiers
        for both buyer and seller sides. These IDs identify the distribution companies
        (discoms) that the buyer and seller are connected to, NOT the customer IDs.
      allOf:
        - $ref: '#/components/schemas/EnergyTradeOrder'
        - type: object
          required: [utilityIdBuyer, utilityIdSeller]
          properties:
            utilityIdBuyer:
              type: string
              description: >
                Identifier of the buyer-side utility/distribution company (discom).
                This is the discom that the energy buyer is connected to for grid access.
                NOT the buyer's customer ID - use orderItemAttributes.utilityCustomerId for that.
              example: "BESCOM-KA"
              x-jsonld: { "@id": utilityIdBuyer }

            utilityIdSeller:
              type: string
              description: >
                Identifier of the seller-side utility/distribution company (discom).
                This is the discom that the energy seller/prosumer is connected to for grid injection.
                NOT the seller's customer ID - this identifies the distribution company.
              example: "TPDDL-DL"
              x-jsonld: { "@id": utilityIdSeller }
      x-jsonld:
        "@context": ./context.jsonld
        "@type": EnergyTradeOrderInterUtility
