@startuml
hide empty members
set namespaceSeparator none


class ChargingService {
    {field} string <b>connectorType</b> {"CCS2", "Type2", "CHAdeMO", "GB_T"}
    {field} number <b>maxPowerKW</b> {1..500}
    {field} integer <b>socketCount</b> {1..}
    {field} number minPowerKW {0..500}
    {field} boolean reservationSupported = true
    {field} Location serviceLocation
    {field} None[] amenityFeature
    {field} string items {"RESTAURANT", "RESTROOM", "WI-FI", "PARKING"}
    {field} string ocppId
    {field} string evseId
    {field} string roamingNetwork
    {field} string parkingType {"OnStreet", "OffStreet", "Basement", "Mall", "FuelStation", "Office", "Hotel"}
    {field} string connectorId
    {field} string powerType {"AC_SINGLE_PHASE", "AC_3_PHASE", "DC"}
    {field} string connectorFormat {"SOCKET", "CABLE"}
    {field} string chargingSpeed {"SLOW", "NORMAL", "FAST", "ULTRAFAST"}
    {field} string stationStatus {"Available", "Occupied", "OutOfService"}
}

ChargingService ..> Location

@enduml
